=== LukeMS/daimonin/trunk/arch/dev/editor/conf/spells.dtd
<?xml version="1.0" encoding="utf-8"?>
<!-- Document Type Definition External Subset for Daimonin spells file.
  - Author: <a href="mailto:chris@itcqis.com">Christian Hujer</a>
  -->

<!-- spells
  - Containts: spell elements (any number)
  -->
<!ELEMENT spells (spell*)>

<!-- spell defines a single spell with its number.
  - @id must be a unique number, starting with 0.
  - @name must be a string
  -->
<!ELEMENT spell EMPTY>
<!ATTLIST spell
    id   CDATA #REQUIRED
    name CDATA #REQUIRED
>

=== LukeMS/daimonin/trunk/arch/dev/editor/conf/spells.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE spells SYSTEM "spells.dtd">
<spells>
<!--
  ##########################################################
  #   You may add new spells to this file, but there's no  #
  #  need to do it because the file can be autogenerated.  #
  # In the editor, select menu "Resources->Collect Spells" #
  #        to generate a new version of this file.         #
  ##########################################################
-->
  <spell id="11"  name="cause light wounds" />
  <spell id="12"  name="confuse" />
  <spell id="4"   name="cure disease" />
  <spell id="3"   name="cure poison" />
  <spell id="8"   name="detect curse" />
  <spell id="7"   name="detect magic" />
  <spell id="0"   name="firestorm" />
  <spell id="1"   name="icestorm" />
  <spell id="6"   name="identify" />
  <spell id="13"  name="magic bullet" />
  <spell id="2"   name="minor healing" />
  <spell id="16"  name="probe" />
  <spell id="9"   name="remove curse" />
  <spell id="10"  name="remove damnation" />
  <spell id="15"  name="remove depletion" />
  <spell id="5"   name="strength self" />
  <spell id="14"  name="summon golem" />
</spells>
