=== LukeMS/daimonin/arch/dev/editor/conf/ArchObjectMatchers.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ENTITY % Match "(And|Or|Attrib|TypeNrs)">
<!ENTITY % Matches "%Match;+">

<!ELEMENT ArchObjectMatchers (ArchObjectMatcher+)>
<!ELEMENT ArchObjectMatcher (title+,%Match;)>
<!ATTLIST ArchObjectMatcher
    id CDATA #IMPLIED
>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
    xml:lang CDATA #REQUIRED
>

<!ELEMENT And (%Matches;)>
<!ELEMENT Or (%Matches;)>

<!ELEMENT Attrib EMPTY>
<!ATTLIST Attrib
    useDefArch (true|false) 'true'
    name NMTOKEN #REQUIRED
    value CDATA '1'
    op (eq|ne|ge|gt|le|lt) 'eq'
>

<!ELEMENT TypeNrs EMPTY>
<!ATTLIST TypeNrs
    numbers CDATA #REQUIRED
>

=== LukeMS/daimonin/arch/dev/editor/conf/ArchObjectMatchers.xml
<?xml version="1.0"?>
<!DOCTYPE ArchObjectMatchers SYSTEM "ArchObjectMatchers.dtd">
<ArchObjectMatchers>
    <ArchObjectMatcher>
        <title xml:lang="en">Background</title>
        <title xml:lang="de">Hintergrund</title>
        <And>
            <Attrib name="is_floor" />
            <Attrib name="no_pick" />
        </And>
    </ArchObjectMatcher>
    <ArchObjectMatcher>
        <title xml:lang="en">Monsters</title>
        <title xml:lang="de">Monster</title>
        <Or>
            <TypeNrs numbers="80 81 83" />
            <Attrib name="monster" />
            <Attrib name="generator" />
        </Or>
    </ArchObjectMatcher>
    <ArchObjectMatcher>
        <title xml:lang="en">Wall</title>
        <title xml:lang="de">Wände</title>
        <And>
            <TypeNrs numbers="77 79" />
            <Attrib name="no_pass" />
        </And>
    </ArchObjectMatcher>
    <ArchObjectMatcher>
        <title xml:lang="en">Connected</title>
        <title xml:lang="de">Verbunden</title>
        <Attrib name="connected" op="ne" value="0" />
    </ArchObjectMatcher>
    <ArchObjectMatcher>
        <title xml:lang="en">Exits</title>
        <title xml:lang="de">Ausgänge</title>
        <TypeNrs numbers="41 66 69 94 95" />
    </ArchObjectMatcher>
    <ArchObjectMatcher>
        <title xml:lang="en">Treasure</title>
        <title xml:lang="de">Schätze</title>
        <And>
            <TypeNrs numbers="4 5 36 60 85 111 123 124 130" />
            <Attrib name="no_pick" value="0" />
        </And>
    </ArchObjectMatcher>
    <ArchObjectMatcher>
        <title xml:lang="en">Doors and Keys</title>
        <title xml:lang="de">Türen und Schlüssel</title>
        <TypeNrs numbers="20 23 26 91 21 24" />
    </ArchObjectMatcher>
    <ArchObjectMatcher>
        <title xml:lang="en">Equipment</title>
        <title xml:lang="de">Ausrüstung</title>
        <And>
            <TypeNrs numbers="3 13 14 15 16 33 34 35 39 70 87 99 100 104 109 113 122" />
            <Attrib name="no_pick" value="0" />
        </And>
    </ArchObjectMatcher>
</ArchObjectMatchers>
