=== LukeMS/daimonin/arch/dev/editor/conf/GameObjectMatchers.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ENTITY % Match "(And|Or|Attrib|TypeNrs)">
<!ENTITY % Matches "%Match;+">

<!ELEMENT GameObjectMatchers (GameObjectMatcher+)>
<!ELEMENT GameObjectMatcher (title+,%Match;)>
<!ATTLIST GameObjectMatcher
    id CDATA #IMPLIED
    system (true|false) 'false'
>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
    xml:lang CDATA #REQUIRED
>

<!ELEMENT And (%Matches;)>
<!ELEMENT Or (%Matches;)>

<!ELEMENT Attrib EMPTY>
<!ATTLIST Attrib
    useArchetype (true|false) 'true'
    name NMTOKEN #REQUIRED
    value CDATA '1'
    op (eq|ne|ge|gt|le|lt) 'eq'
>

<!ELEMENT TypeNrs EMPTY>
<!ATTLIST TypeNrs
    numbers CDATA #REQUIRED
>

=== LukeMS/daimonin/trunk/arch/dev/editor/conf/GameObjectMatchers.xml
<?xml version="1.0"?>
<!DOCTYPE GameObjectMatchers SYSTEM "GameObjectMatchers.dtd">
<GameObjectMatchers>

    <GameObjectMatcher id="monster">
        <title xml:lang="en">Monster</title>
        <title xml:lang="de">Monster</title>
        <title xml:lang="fr">Monstres</title>
        <title xml:lang="sv">Monster</title>
        <Or>
            <TypeNrs numbers="80 81 83" />
            <Attrib name="monster" />
        </Or>
    </GameObjectMatcher>

    <GameObjectMatcher id="floormask">
        <title xml:lang="en">Floormask</title>
        <title xml:lang="de">Bodenmasken</title>
        <And>
            <TypeNrs numbers="28" />
            <Attrib name="layer" value="2" />
        </And>
    </GameObjectMatcher>

    <GameObjectMatcher id="floor">
        <title xml:lang="en">Floor</title>
        <title xml:lang="de">Boden</title>
        <And>
            <TypeNrs numbers="71" />
            <Attrib name="layer" value="1" />
        </And>
    </GameObjectMatcher>

    <GameObjectMatcher id="wall">
        <title xml:lang="en">Wall</title>
        <title xml:lang="de">Wand</title>
        <title xml:lang="fr">Murs</title>
        <title xml:lang="sv">Väggar</title>
        <Or>
            <TypeNrs numbers="77" />
            <Attrib name="no_pass" />
        </Or>
    </GameObjectMatcher>

    <GameObjectMatcher id="connected">
        <title xml:lang="en">Connected</title>
        <title xml:lang="de">Verbunden</title>
        <title xml:lang="fr">Objets connectés</title>
        <title xml:lang="sv">Anslutna</title>
        <And>
            <Attrib name="connected" op="ne" value="" />
            <Attrib name="connected" op="ne" value="0" />
        </And>
    </GameObjectMatcher>

    <GameObjectMatcher id="exit">
        <title xml:lang="en">Exit</title>
        <title xml:lang="de">Ausgang</title>
        <title xml:lang="fr">Sorties</title>
        <title xml:lang="sv">Utgångar</title>
        <TypeNrs numbers="41 66 69 94 95" />
    </GameObjectMatcher>

    <GameObjectMatcher id="treasure">
        <title xml:lang="en">Treasure</title>
        <title xml:lang="de">Schatz</title>
        <title xml:lang="fr">Trésors</title>
        <title xml:lang="sv">Skatter</title>
        <And>
            <TypeNrs numbers="4 5 36 60 85 111 130" />
            <Or>
                <Attrib name="no_pick" value="" />
                <Attrib name="no_pick" value="0" />
            </Or>
        </And>
    </GameObjectMatcher>

    <GameObjectMatcher id="door">
        <title xml:lang="en">Doors and Keys</title>
        <title xml:lang="de">Türen und Schlüssel</title>
        <title xml:lang="fr">Portes et Clés</title>
        <title xml:lang="sv">Dörrar och Nycklar</title>
        <TypeNrs numbers="20 21 23 24 26 91" />
    </GameObjectMatcher>

    <GameObjectMatcher id="equipment">
        <title xml:lang="en">Equipment</title>
        <title xml:lang="de">Ausrüstung</title>
        <title xml:lang="fr">Équipement</title>
        <title xml:lang="sv">Utrustning</title>
        <And>
            <TypeNrs numbers="3 13 14 15 16 33 34 35 39 70 87 99 100 104 109 113 122" />
            <Or>
                <Attrib name="no_pick" value="" />
                <Attrib name="no_pick" value="0" />
            </Or>
        </And>
    </GameObjectMatcher>

    <GameObjectMatcher id="event_object">
        <title xml:lang="en">Event Object</title>
        <title xml:lang="de">Ereignisgegenstand</title>
        <title xml:lang="fr">Objet d'Événement</title>
        <Env />
        <TypeNrs numbers="118" />
    </GameObjectMatcher>

    <!-- Objects to be treated as floors in insertion tool -->
    <GameObjectMatcher id="system_floor" system="true">
        <title xml:lang="en">Floor</title>
        <title xml:lang="de">Boden</title>
        <TypeNrs numbers="65 71" />
    </GameObjectMatcher>

    <!-- Objects to be put below the floor in insertion tool -->
    <GameObjectMatcher id="system_below_floor" system="true">
        <title xml:lang="en">Below Floor</title>
        <title xml:lang="de">Unter Boden</title>
        <TypeNrs numbers="-666" />
        <!-- <Attrib name="layer" value="0" /> -->
    </GameObjectMatcher>

    <!-- Objects to be put below the floor in insertion tool -->
    <GameObjectMatcher id="system_wall" system="true">
        <title xml:lang="en">Wall</title>
        <title xml:lang="de">Wand</title>
        <title xml:lang="fr">Murs</title>
        <title xml:lang="sv">Väggar</title>
        <And>
            <TypeNrs numbers="77" />
            <Attrib name="layer" value="7" op="ne" />
        </And>
    </GameObjectMatcher>

    <!-- Objects to be treated as monsters in insertion tool -->
    <GameObjectMatcher id="system_monster" system="true">
        <title xml:lang="en">Monster</title>
        <title xml:lang="de">Monster</title>
        <title xml:lang="fr">Monstres</title>
        <title xml:lang="sv">Monster</title>
        <Or>
            <TypeNrs numbers="80 81 83" />
            <Attrib name="monster" />
        </Or>
    </GameObjectMatcher>

    <!-- Objects to be treated as exits by the GUI -->
    <GameObjectMatcher id="system_exit" system="true">
        <title xml:lang="en">Exit</title>
        <title xml:lang="de">Ausgang</title>
        <title xml:lang="fr">Sorties</title>
        <title xml:lang="sv">Utgångar</title>
        <TypeNrs numbers="41 66 69 94 95" />
    </GameObjectMatcher>

    <!-- Objects to be checked by the "Critical slaying characters" map
         validator. -->
    <GameObjectMatcher id="system_environment_sensor" system="true">
        <title xml:lang="en">Environment Sensor</title>
        <title xml:lang="de">Umgebungs-Sensor</title>
        <TypeNrs numbers="133" />
    </GameObjectMatcher>

    <GameObjectMatcher id="system_monster_only" system="true">
        <title xml:lang="en">Monster Only</title>
        <title xml:lang="de">Nur Monster</title>
        <TypeNrs numbers="80 83" />
    </GameObjectMatcher>

    <GameObjectMatcher id="system_combat_values_objects" system="true">
        <title xml:lang="en">Objects using &quot;combat_values&quot;</title>
        <title xml:lang="de">Objekte mit &quot;combat_values&quot;</title>
        <TypeNrs numbers="5 6 7 13 39 54 62 72 73 80 83 154 158" />
    </GameObjectMatcher>

    <!-- Objects checked by the "Suspicious connection" map validator: objects
         matching this matcher are connection sources. -->
    <GameObjectMatcher id="system_connection_source" system="true">
        <title xml:lang="en">Connected objects being a source</title>
        <title xml:lang="de">Verbundene Objekte (Quellen)</title>
        <TypeNrs numbers="17 18 27 30 31 32 51 64 92 93 132 133 134" />
    </GameObjectMatcher>

    <!-- Objects checked by the "Suspicious connection" map validator: objects
         matching this matcher are connection sinks. -->
    <GameObjectMatcher id="system_connection_sink" system="true">
        <title xml:lang="en">Connected objects being a sink</title>
        <title xml:lang="de">Verbundene Objekte (Senken)</title>
        <Or>
            <TypeNrs numbers="26 41 42 55 62 65 74 78 81 91 94 98 112 132" />
        </Or>
    </GameObjectMatcher>

    <!-- Objects checked by the "Suspicious connection" map validator: objects
         matching this matcher are connection sinks. This matcher exists in
         order to match inventory objects since &lt;Env&gt; cannot be included
         into &lt;Or&gt;. -->
    <GameObjectMatcher id="system_connection_sink2" system="true">
        <title xml:lang="en">Connected objects being a sink</title>
        <title xml:lang="de">Verbundene Objekte (Senken)</title>
        <Env/>
        <TypeNrs numbers="-666" />
    </GameObjectMatcher>

</GameObjectMatchers>
