<?xml version="1.0" standalone="no" ?>
<!--
######################################################################
# types.xml - This is the defintitions-file for all the different    #
# Daimonin object types and their attributes.                        #
#                                                                    #
# The server code of the Daimonin game is always changing and        #
# evlolving. From time to time, object-attributes change in purpose, #
# or new ones are created.                                           #
# Therefore, it is important that an Editor is flexible and          #
# easy to "upgrade" to handle such new features. That's why the      #
# DaimoninEditor reads the type-definitions from this xml file.      #
#                                                                    #
# If you encounter bugs, typos or missing entrys in the LATEST       #
# VERSION of this file - Don't hesitate to improve it, contact me    #
# and eventually send the improved file to me: <red.blaze@gmx.net>.  #
# I will put it into the "official version" of the DaimoninEditor    #
# and all fellow Daimonin-Map-Makers can benefit from your work!     #
#                                                                    #
# IMPORTANT: Make a backup copy of this file before you start        #
# to modify it!                                                      #
#                                                                    #
# New types must be inserted maintaining the alphabetical order.     #
#                                                                    #
# about the 'type' elements:                                         #
#                                                                    #
# <type number="15" name="Type Name">                                #
# <import_type name="Type Name" />   import attributes of this type  #
# <required>                                                         #
#    list of required attributes to identifying this type            #
# </required>                                                        #
# <ignore>                                                           #
#    list of attributes not to import from default_type              #
# </ignore>                                                          #
# <description><![CDATA[                                             #
#   Description of this type. ]]>                                    #
# </description>                                                     #
# <use><![CDATA[                                                     #
#   How to use this type. ]]>                                        #
# </use>                                                             #
# ... attributes ...                                                 #
# </type>                                                            #
#                                                                    #
# about the 'attribute' type: <attribute ... type="XXX" >            #
#                                                                    #
# bool         - This attribute can only be set to '1' or '0'        #
# int          - This attribute contains a decimal number            #
# float        - This attr. contains a floating point number         #
# string       - This attribute contains a string                    #
# text         - This attribute contains a text ("text" can have     #
#                linebreaks, unlike "string")                        #
# fixed        - This attribute is always set to a fixed 'value'     #
#                (There is no user-input for this attribute)         #
# spell        - This attribute contains a spell. The mapmaker can   #
#                choose spells from a combo box.                     #
# nz_spell     - works just like 'spell', except that the            #
#                spell-value zero is always interpreted as <none>,   #
#                never as "magic bullet"                             #
# bool_special - Like bool, but with customized true/false values    #
# treasurelist - CF treasure list (see "treasures" file)             #
# list_LISTNAME       - list, must be defined as a <list> element    #
# bitmask_BITMASKNAME - bitmask, must be defined as a <bitmask>      #
#                       element                                      #
#                                                                    #
# Created by Andreas Vogl.                                           #
######################################################################
-->
<!DOCTYPE types [
  <!ELEMENT types ((bitmask | list | ignore_list)*, default_type, ignore_list*, type+)>

  <!ELEMENT bitmask (entry*)>
  <!ATTLIST bitmask name CDATA #REQUIRED>

  <!ELEMENT list (entry*)>
  <!ATTLIST list name CDATA #REQUIRED>

  <!ELEMENT entry EMPTY>
  <!ATTLIST entry bit   CDATA #IMPLIED
                  value CDATA #IMPLIED
                  name  CDATA #REQUIRED>
  
  <!ELEMENT ignore_list (attribute* | EMPTY)>
  <!ATTLIST ignore_list name CDATA #REQUIRED>
  
  <!ELEMENT default_type (attribute*)>
  
  <!ELEMENT type (import_type?,required?,ignore?,description?,use?,(section | attribute)*)>
  <!ATTLIST type name   CDATA #REQUIRED
                 number CDATA #REQUIRED>
  
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT use (#PCDATA)>
  
  <!ELEMENT import_type EMPTY>
  <!ATTLIST import_type name CDATA #REQUIRED>
  
  <!ELEMENT required (attribute+)>
  <!ELEMENT ignore (attribute*,ignore_list*)>
  
  <!ELEMENT section (attribute+)>
  <!ATTLIST section name CDATA #REQUIRED>
  
  <!ELEMENT attribute (#PCDATA)>
  <!ATTLIST attribute type       CDATA #IMPLIED
                      arch       CDATA #IMPLIED
                      arch_begin CDATA #IMPLIED
                      arch_end   CDATA #IMPLIED
                      editor     CDATA #IMPLIED
                      value      CDATA #IMPLIED
                      length     CDATA #IMPLIED
                      true       CDATA #IMPLIED
                      false      CDATA #IMPLIED>
]>

<types>

<!--###################### bitmask definitions ######################-->

<bitmask name="material">
  <entry bit="0"  name="Paper" />
  <entry bit="1"  name="Hard Metal" />
  <entry bit="2"  name="Crystal" />
  <entry bit="3"  name="Leather" />
  <entry bit="4"  name="Wood" />
  <entry bit="5"  name="Organics" />
  <entry bit="6"  name="Stone" />
  <entry bit="7"  name="Cloth" />
  <entry bit="8"  name="Magic Material" />
  <entry bit="9"  name="Liquid" />
  <entry bit="10" name="Soft Metal" />
  <entry bit="11" name="Bone" />
  <entry bit="12" name="Ice" />
</bitmask>

<bitmask name="spellpath">
  <entry bit="0" name="Protection" />
  <entry bit="1" name="Fire" />
  <entry bit="2" name="Frost" />
  <entry bit="3" name="Electricity" />
  <entry bit="4" name="Missiles" />
  <entry bit="5" name="Self" />
  <entry bit="6" name="Summoning" />
  <entry bit="7" name="Abjuration" />
  <entry bit="8" name="Restoration" />
  <entry bit="9" name="Detonation" />
  <entry bit="10" name="Mind" />
  <entry bit="11" name="Creation" />
  <entry bit="12" name="Teleportation" />
  <entry bit="13" name="Information" />
  <entry bit="14" name="Transmutation" />
  <entry bit="15" name="Transferrence" />
  <entry bit="16" name="Turning" />
  <entry bit="17" name="Wounding" />
  <entry bit="18" name="Death" />
  <entry bit="19" name="Light" />
</bitmask>

<bitmask name="will_apply">
  <entry bit="0" name="Apply Handles" />
  <entry bit="1" name="Open Chests" />
  <entry bit="2" name="Break Walls" />
  <entry bit="3" name="Open Doors" />
</bitmask>

<bitmask name="pick_up">
  <entry bit="0" name="Nothing" />
  <entry bit="1" name="Wealth" />
  <entry bit="2" name="Food" />
  <entry bit="3" name="Weapons" />
  <entry bit="4" name="Armour" />
  <entry bit="5" name="Inverse" />
  <entry bit="6" name="All" />
</bitmask>

<bitmask name="terrain">
  <entry bit="0" name="Land Surface" />
  <entry bit="1" name="Water Surface" />
  <entry bit="2" name="Under Water" />
  <entry bit="3" name="Fire Surface" />
  <entry bit="4" name="Under Fire" />
  <entry bit="5" name="Cloud Surface" />
</bitmask>

<!--###################### list definitions ######################-->

<list name="language">
  <entry value="0"  name="common" />
  <entry value="1"  name="dwarvish" />
  <entry value="2"  name="ancient dwarvish" />
  <entry value="4"  name="elvish" />
  <entry value="8"  name="high elvish" />
  <entry value="16"  name="drow" />
  <entry value="32"  name="gnomish" />
  <entry value="64"  name="old council" />
  <entry value="128"  name="elder pictograms" />
  <entry value="256"  name="chaotic" />
  <entry value="512" name="evil runic" />
  <entry value="1024" name="runic" />
  <entry value="2048" name="dragonish" />
  <entry value="4096" name="jotun" />
  <entry value="8192" name="high planar" />
  <entry value="16384" name="orc runes" />
</list>

<list name="event">
  <entry value="0" name="no event" />
  <entry value="1" name="apply" />
  <entry value="2" name="attack" />
  <entry value="3" name="death" />
  <entry value="4" name="drop" />
  <entry value="5" name="pickup" />
  <entry value="6" name="say" />
  <entry value="7" name="stop" />
  <entry value="8" name="time" />
  <entry value="9" name="throw" />
  <entry value="10" name="trigger" />
  <entry value="11" name="close" />
  <entry value="12" name="timer" />
  <entry value="13" name="talk" />
</list>

<list name="direction">
  <entry value="0" name="&lt;none&gt;" />
  <entry value="1" name="north" />
  <entry value="2" name="northeast" />
  <entry value="3" name="east" />
  <entry value="4" name="southeast" />
  <entry value="5" name="south" />
  <entry value="6" name="southwest" />
  <entry value="7" name="west" />
  <entry value="8" name="northwest" />
</list>

<list name="mood">
  <entry value="0" name="furious" />
  <entry value="1" name="angry" />
  <entry value="2" name="calm" />
  <entry value="3" name="sleep" />
  <entry value="4" name="charm" />
</list>

<list name="item_race">
  <entry value="0" name="&lt;none&gt;" />
  <entry value="1" name="dwarven" />
  <entry value="2" name="elven" />
  <entry value="3" name="gnomish" />
  <entry value="4" name="drow" />
  <entry value="5" name="orcish" />
  <entry value="6" name="goblin" />
  <entry value="7" name="kobold" />
  <entry value="8" name="giant" />
  <entry value="9" name="tiny" />
  <entry value="10" name="genie" />
  <entry value="11" name="demonish" />
  <entry value="12" name="dragon" />
</list>

<list name="q_trigger">
  <entry value="0" name="normal" />
  <entry value="1" name="kill quest" />
  <entry value="2" name="container quest" />
</list>

<list name="potion_effect">
  <entry value="0" name="&lt;none&gt;" />
  <entry value="65536" name="life restoration" />
  <entry value="1048576" name="improvement" />
</list>

<list name="item_skill">
  <entry value="0" name="&lt;overall level&gt;" />
  <entry value="1" name="agility" />
  <entry value="2" name="personality" />
  <entry value="3" name="mental" />
  <entry value="4" name="physical" />
  <entry value="5" name="magic" />
  <entry value="6" name="wisdom" />
</list>

<list name="weapon_st">
  <entry value="0" name="1 handed impact weapon" />
  <entry value="1" name="1 handed slash weapon" />
  <entry value="2" name="1 handed pierce weapon" />
  <entry value="3" name="1 handed cleave weapon" />
  <entry value="4" name="2 handed impact weapon" />
  <entry value="5" name="2 handed slash weapon" />
  <entry value="6" name="2 handed pierce weapon" />
  <entry value="7" name="2 handed cleave weapon" />
  <entry value="8" name="impact polearm" />
  <entry value="9" name="slash polearm" />
  <entry value="10" name="pierce polearm" />
  <entry value="11" name="cleave polearm" />
</list>

<list name="shootweapon_st">
  <entry value="0" name="bow" />
  <entry value="1" name="crossbow" />
  <entry value="2" name="sling" />
  <entry value="3" name="firearm" />
</list>


<list name="projectile_st">
  <entry value="0"   name="&lt;unknown&gt;" />
  <entry value="1"   name="arrow" />
  <entry value="2"   name="crossbow bolt" />
  <entry value="3"   name="sling stone" />
  <entry value="128" name="throwing impact weapons" />
  <entry value="129" name="throwing slash weapons" />
  <entry value="130" name="throwing pierce weapons" />
  <entry value="131" name="throwing cleave weapons" />
  <entry value="132" name="throwing boulders" />
</list>

<list name="material_real">
  <entry value="0" name="&lt;undefined&gt;" />
  <entry value="1" name="paper: standard paper" />
  <entry value="2" name="paper: parchment" />
  <entry value="65" name="hard metal: iron" />
  <entry value="66" name="hard metal: hard iron" />
  <entry value="67" name="hard metal: steel" />
  <entry value="68" name="hard metal: forged steel" />
  <entry value="69" name="hard metal: dark steel" />
  <entry value="70" name="hard metal: forged dark steel" />
  <entry value="71" name="hard metal: silksteel" />
  <entry value="72" name="hard metal: forged silksteel" />
  <entry value="129" name="crystal: glass" />
  <entry value="130" name="crystal: zircon" />
  <entry value="131" name="crystal: pearl" />
  <entry value="132" name="crystal: emerald" />
  <entry value="133" name="crystal: sapphire" />
  <entry value="134" name="crystal: ruby" />
  <entry value="135" name="crystal: diamond" />
  <entry value="193" name="leather: soft leather" />
  <entry value="194" name="leather: hardened leather" />
  <entry value="195" name="leather: ogre leather" />
  <entry value="196" name="leather: giant leather" />
  <entry value="197" name="leather: dark leather" />
  <entry value="198" name="leather: drow leather" />
  <entry value="199" name="leather: demon leather" />
  <entry value="200" name="leather: dragon leather" />
  <entry value="257" name="wood: polished" />
  <entry value="258" name="wood: oak wood" />
  <entry value="321" name="organic: animal organics" />
  <entry value="322" name="organic: dragon organics" />
  <entry value="385" name="stone: flint" />
  <entry value="449" name="cloth: wool" />
  <entry value="450" name="cloth: linen" />
  <entry value="451" name="cloth: silk" />
  <entry value="452" name="cloth: elven hair" />
  <entry value="513" name="adamant: magic silk" />
  <entry value="514" name="adamant: mithril" />
  <entry value="515" name="adamant: adamant" />
  <entry value="577" name="liquid: (default liquid)" />
  <entry value="641" name="soft metal: tin" />
  <entry value="642" name="soft metal: brass" />
  <entry value="643" name="soft metal: copper" />
  <entry value="644" name="soft metal: bronze" />
  <entry value="645" name="soft metal: silver" />
  <entry value="646" name="soft metal: gold" />
  <entry value="647" name="soft metal: platinum" />
  <entry value="705" name="bone: animal bone" />
  <entry value="706" name="bone: human bone" />
  <entry value="707" name="bone: elven bone" />
  <entry value="708" name="bone: dwarven bone" />
  <entry value="769" name="ice: (default ice)" />
</list>

<list name="attack_type">

  <entry value="0" name="&lt;standard&gt;" />

  <entry value="1" name="Distance attack" />

  <entry value="2" name="Run away" />

  <entry value="3" name="Hit and run" />

  <entry value="4" name="Wait and hit" />

  <entry value="5" name="Always run" />

  <entry value="6" name="Wait and hit from distance" />

  <entry value="7" name="Keep distance" />

</list>



<list name="move_type">

  <entry value="0" name="&lt;standard&gt;" />

  <entry value="16" name="Pet movement" />

  <entry value="32" name="Small circle" />

  <entry value="48" name="Large circle" />

  <entry value="64" name="Short horiz pace" />

  <entry value="80" name="Long horiz pace" />

  <entry value="96" name="Random direction" />

  <entry value="112" name="Random walk" />

  <entry value="128" name="Short vert pace" />

  <entry value="144" name="Long vert pace" />

  <entry value="176" name="Use waypoints" />

</list> 

<!--###################### default attributes ######################-->

<!--
  The attributes of the default_type get added to all other types by default.
  Every type can have an 'ignore' element however, which is used to specify
  default attributes *not* to inherit.
  -->
<default_type>
  <attribute arch="name" editor="name" type="string">
    This is the name of the object, displayed to the player.
  </attribute>
  <attribute arch="title" editor="title" type="string">
    This is the object's title. Once an object is identified the title is
    attached to the name. Typical titels are "of mostrai", "of xray vision" etc.
  </attribute>
  <attribute arch="sub_type" editor="sub type" type="int">
    This important value is used to define "sub types" for objects of the same object
    type. Examples are weapons, which are all from type WEAPON but can be different sub types
    like slash type, cleave type, 1hand, polearms and so on. This value goes to the client
    too. WARNING: not all objects have a sub_type and changing it without care can corrupt
    server AND/OR the clients. Normally this is not a subject to change outside arch definition.
  </attribute>
  <attribute arch="layer" editor="layer" type="int">
    This is the map layer, the object will put in. The selected layer will effect where and
    how this object is shown on client side. Layer 0 is reserved for sys_object type objects
    and will NEVER be shown on client side. Layer 1 is for floor objects and Layer 2 for
    floor masks. Layer 3 and 4 are for items on the ground. Layer 5 is for walls, layer 
    6 is reversed for players and layer 7 is for spell effects and high flying/visible
    objects like arrows.
  </attribute>
  <attribute arch="face" editor="image" type="string">
    The image-name defines what image is displayed for this object
    in-game.
  </attribute>
  <attribute arch="animation" editor="animation" type="string">
    The animation-name defines what animation is displayed for this object
    in-game. Note that a set animation will overrule the face.
    Changing animation is easy - adding or deleting a animation is more
    difficult and should be done in the text parse window and not in this
    dialog.
  </attribute>
  <attribute arch="anim_speed" editor="anim speed" type="int">
  How fast to play this animation.
  </attribute>
  <attribute arch="is_animated" editor="is animated" type="bool">
  If set, the object is animated and animation is used.
  Note: Some special objects will use a animation NOT as animation but
  as frame list. Examples are buttons (which frames are changed by the
  object status of the button). IS_TURNABLE will enable direction turning
  for some object types. These flags are all "system" related. Be VERY
  careful to change them.
  </attribute>
  <attribute arch="speed_left" editor="start speed" type="float">
    NOTE: without speed != 0, this value is not used. Only use
    for objects with speed (active objects)!
    When a active object (with 'speed' != 0) is put on a map, this 
    value is used as counter. Every 'tick', 'speed' (if negative,
    value is turned positive before) is added to this value - 
    if it is bigger 0 the object 'will do something' and this counter is 
    decreased with -1.0 .
    As default a normal object will put on the map with start speed 0. 
    It 'will do something' with the next coming 'tick'.
    Setting this value to -1.0 will put it on map but wait one full 
    'lifetime' round until it does something. 
    A 'fire object' should be put on map with start speed 0 - it should
    try to burn something in the moment it comes in the game. A bomb for
    example should be put with speed -1.0 on the map - it will stay then
    on map until the bomb becomes active - it explode.
    The 'lifetime' round is determinated by speed. A speed of 1.0 will
    give a 'lifetime' round of 1 tick - a speed of 0.01 100 ticks.
    Special case: A negative speed value will add to start speed a random
    value between 0.0 to 0.9 . So, a speed of -0.1 with a start speed of
    -1.0 will result in speed 0.1 and start speed between -1.0 and -0.1. 
    This is useful to lets a row of same objects act in different tick ranges.
  </attribute>
  <attribute arch="nrof" editor="number" type="int">
    This value determines the number of objects in one stack (for example:
    100 goldcoins =&gt; "number = 100"). You should set this at least to one, for
    any pickable object - otherwise it won't be mergeable into a stack.
  </attribute>
  <attribute arch="weight" editor="weight" type="int">
    This value defines the object's weight in gramm (1000g is 1kg). Objects with
    zero weight are not pickable for players. Still, set the "non-pickable"-flag
    for explicitly non-pickable objects (hey, this is opensource.. you
    never know ;) ).
  </attribute>
  <attribute arch="value" editor="value" type="int">
    Adds a certain value to the object: It will be worth that many times the
    default value from it's archetype (E.g. "value = 3" means three times
    worth the default value). Value for buying/selling will be
    further modified by various factors. Hence, testing values in-game is
    usually inevitable.
  </attribute>
  <attribute arch="glow_radius" editor="glow radius" type="int">
    If &lt;glow radius&gt; is set to a value greater zero, the object
    appears lit up on dark maps. &lt;glow radius&gt; can be a value
    between 0 and 4, the higher, the more light does the object emmit.
  </attribute>
  <attribute arch="material_real" editor="material" type="list_material_real">
    The material defines the exact material of which the object
    consists. It is much more specific than &lt;material class&gt;,
    however only one material can be selected, not multiple.
    &lt;material&gt; is not required to be set, it can be left 'undefined'.
  </attribute>
  <attribute arch="material" editor="material class" type="bitmask_material">
    This bitmask-value informs the player of which basic material(s)
    the object consists. Material class does also affect how likely the
    object can be destroyed by hazardous spell-effects.
  </attribute>
  <attribute arch="no_pick" editor="non-pickable" type="bool">
    If set, the object cannot be picked up (Neither by players nor monsters).
  </attribute>
  <attribute arch="player_only" editor="player only" type="bool">
    If set, only players can enter the tile the object with this flag is in too.
  </attribute>
  <attribute arch="is_ethereal" editor="ethereal (pass thru)" type="bool">
    If no_pass (blocking passage) is set for a object, no one can pass
    the tile is it in (true for walls or closed doors). But if this
    flag is set, the monster can pass through all no_pass objects
    which has pass_thru set. 
    This is used for example from ghosts who moves through doors.
    Be careful! This is a extrem powerful ability! Use it in context!
    Orcs who moves without reason through walls are not senseful.
    NOTE: ethereal has special abilities. It has the same effect
    like can_pass_thru flag but its special. Its like the difference
    between a being make out of dust (which is still kind of matter)
    and a real ghost which is pure energy.
  </attribute>
  <attribute arch="pass_ethereal" editor="etheral can pass" type="bool">
    If no_pass (blocking passage) is set, no one can pass. If this
    flag is set too, etheral flaged objects and CAN_PASS_THRU flag can pass.
  </attribute>
  <attribute arch="can_pass_thru" editor="pass thru blocked" type="bool">
    If no_pass (blocking passage) is set for a object, no one can pass
    the tile is it in (true for walls or closed doors). But if this
    flag is set, the monster can pass through all no_pass objects
    which has pass_thru set. 
    This is used for example from ghosts who moves through doors.
    Be careful! This is a extrem powerful ability! Use it in context!
    Orcs who moves without reason through walls are not senseful.
    NOTE: can_pass_thru is a sub-effect from ethereality. See below.
  </attribute>
  <attribute arch="pass_thru" editor="can pass (no ethereal)" type="bool">
    If no_pass (blocking passage) is set, no one can pass. If this
    flag is set too, objects with the CAN_PASS_THRU flag can pass.
    Ethereal can't pass this as long pass_ethereal is not set!
  </attribute>
  <attribute arch="is_invisible" editor="invisible" type="bool">
    Generally makes the object invisible. Invisible objects will be shown
    if the player has "see invisible" (from spell or item). To hide objects
    totally from detection, use "sys_object".
  </attribute>
  <attribute arch="sys_object" editor="inv. system object" type="bool">
    Marks an object as system object. System objects are ALWAYS invisible and
    hidden from the players. They can't be seen or detected and never will send
    any information about them to the players client. System objects are put
    in layer 0 under the floor tiles.
  </attribute>
  <attribute arch="no_teleport" editor="no teleport" type="bool">
    Marks an object as no teleport object. A no teleport object can't be
    teleported by teleporter except the object is inside the inventory of 
    another object which can be teleported.
  </attribute>
  <attribute arch="blocksview" editor="block view" type="bool">
    If an item is set to block view, players (and monsters) cannot
    see byond it unless they cross it or manage to stand ontop.
  </attribute>
  <attribute arch="one_drop" editor="one drop" type="bool">
   In the moment a player gets or apply this items, it will
   flaged as godgiven and vanish when droped to the ground.
  </attribute>
  <attribute arch="quest_item" editor="quest item" type="bool">
    Item is a quest item. This item will be inserted in the 
    quest container when a quest is finished and for that player
    this item will never drop again.
  </attribute>
  <attribute arch="inv_locked" editor="inv or quest lock" type="bool">
    Double used flag. Item is locked when in player inventory (can't be
    dropped). It also marks closed (locked) quest info and items.
  </attribute>
  <attribute arch="identified" editor="identified" type="bool">
    If an item is identified, the player has
    full knowledge about it.
  </attribute>
  <attribute arch="can_reflect_spell" editor="can reflect spells" type="bool">
  object CAN reflect spells. See reflect spells.
  </attribute>
  <attribute arch="can_reflect_missile" editor="can reflect missiles" type="bool">
   object CAN reflect missiles. See reflect missiles.
  </attribute>
  <attribute arch="is_magical" editor="magical" type="bool">
    If set, this object count as "magical". Detect magic or
    identify will show this flag and the player will see a small
    M in the client inventory part.
  </attribute>
  <attribute arch="cursed" editor="cursed" type="bool">
    The item is cursed. This object can't be removed when
    wielded or worn (without uncurse it). Remove curse will
    remove this flag.
  </attribute>
  <attribute arch="cursed_perm" editor="permanent cursed" type="bool">
    The item is permanent cursed. If this flag set, applying 
    or unapplying will set "cursed 1" again. This flag can't be
    removed by remove curse.
  </attribute>
  <attribute arch="damned" editor="damned" type="bool">
    Stronger form of curse. Item can't be removed when
    wielded or worn. Remove damnation will remove this flag.
  </attribute>
  <attribute arch="damned_perm" editor="permanent damned" type="bool">
    The item is permanent damned. If this flag set, applying 
    or unapplying will set "damned 1" again. This flag can't be
    removed by remove damnation.
  </attribute>
  <attribute arch="no_magic" editor="no spells" type="bool">
    If enabled, it is impossible for players to use (wizard-)
    spells on that spot.
  </attribute>
  <attribute arch="no_cleric" editor="no prayers" type="bool">
    If enabled, it is impossible for players to use (cleric-)
    prayers on that spot.
  </attribute>
  <attribute arch="unpaid" editor="unpaid" type="bool">
    An &lt;unpaid&gt; item cannot be used unless a player carried it over
    a shop mat, paying the demanded price. Setting this flag makes sense
    only for pickable items inside shops.
  </attribute>
  <attribute arch="is_turnable" editor="is turnable" type="bool">
  System flag. Object can be turned to the directions.
  </attribute>
</default_type>

<!-- This ignorelist is for all system objects which are non pickable
     and invisible. They don't interact with players at all. -->
<ignore_list name="system_object">
  <attribute arch="value" />
  <attribute arch="nrof" />
  <attribute arch="sub_type" />
  <attribute arch="weight" />
  <attribute arch="material" />
  <attribute arch="material_real" />
  <attribute arch="no_pick" />
  <attribute arch="unpaid" />
  <attribute arch="title" />
  <attribute arch="glow_radius" />
  <attribute arch="identified" />
  <attribute arch="blocksview" />
  <attribute arch="is_invisible" />
</ignore_list>

<!-- This ignorelist is for non-pickable objects. They can be seen by
     the player, but don't have values like material or weight. -->
<ignore_list name="non_pickable">
  <attribute arch="value" />
  <attribute arch="nrof" />
  <attribute arch="weight" />
  <attribute arch="material" />
  <attribute arch="material_real" />
  <attribute arch="no_pick" />
  <attribute arch="unpaid" />
  <attribute arch="title" />
  <attribute arch="identified" />
</ignore_list>

<!-- This ignorelist is for all objects. We handle here some very
     special stuff. Note: This values has the same meaning for *ALL*
     object type - they are handled always in the same way.
     NOTE: "direction" is hard coded excluded from syntax check
     in the ArchObject.java module  -->
<ignore_list name="default_setting">
  <attribute arch="xxxx" />
</ignore_list>
